server:
  servlet:
    context-path: /
  port: 685

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mvc:
    view:
      suffix: /,/fore,/back,/test
      prefix: .html
  thymeleaf:
    cache: false
  devtools:
    restart:
      enable: true
      additional-paths: src/main/java
      additional-exclude: static
  datasource:
    url: jdbc:mysql://localhost:3306/mul_amuse?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.skyc.demo.admin.dao, com.skyc.demo.developers.dao, com.skyc.demo.merchants.dao, com.skyc.demo.user.dao
  mapper-locations: classpath:mapper/admin/*.xml, mapper/developers/*.xml, mapper/merchants/*.xml, mapper/user/*.xml
  level:
    com:
      tm:
        huanglu:
          dao:
            factory: debug
            file: debug
            log: debug
            problem: debug
            product: debug
            tm: debug
            user: debug

uploadPath: C:/upload/img

insertSuc: 添加成功！
insertFAL: 添加失败！
updateSuc: 修改成功！
updateFal: 修改失败，请重试！

checkUsername: 用户名未注册!
repeatUsername: 用户名已存在!
checkPass: 请核对密码后重试!